setenv SLURM_NODELIST "worker5025"
setenv SLURM_JOB_NODELIST "worker5025"
setenv SLURM_NNODES 1
setenv SLURM_JOB_NUM_NODES 1
setenv SLURM_JOB_CPUS_PER_NODE "128"
unsetenv SLURM_NPROCS
unsetenv SLURM_NTASKS
unsetenv SLURM_TASKS_PER_NODE
