#!/usr/bin/env python3

try:
    from disbatch import disBatch
except Exception as e:
    import os, sys
    pp = os.environ.get('PYTHONPATH', '<Not Set>')
    print(f'Unable to import disBatch. Check:\n\tPYTHONPATH {pp!r}.\n'
           'Original exception follows.', file=sys.stderr)
    raise e

disBatch.main()
