#!/bin/bash

# Argument list should be the log files from a 4KTasksRep run.

echo "Should be 4000"
echo "$#"
echo "Should be 4007998000"
awk 'FNR == 2{c = c + $1}END{printf("%d\n", c)}' "$@"
echo "Should be 13.00"
awk 'FNR == 3{s = $1}FNR == 4 {c = c + $1 - s}END{printf("%.2f\n", c/4000.)}' "$@"

echo "Now run: awk -F'\t' '{print \$5}' <StatusFile>  | sort | uniq -c "